services:
  cli-proxy-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION:-dev}
        COMMIT: ${COMMIT:-none}
        BUILD_DATE: ${BUILD_DATE:-unknown}
    container_name: cli-proxy-api
    environment:
      DEPLOY: cloud
      MANAGEMENT_PASSWORD: ${MANAGEMENT_PASSWORD:-}
      CLI_PROXY_API_KEYS_JSON: ${CLI_PROXY_API_KEYS_JSON:-}
      CLI_PROXY_CONFIG_YAML: ${CLI_PROXY_CONFIG_YAML:-}
    ports:
      - "8317:8317"
    volumes:
      - "../files/auths:/root/.cli-proxy-api"
      - "../files/logs:/CLIProxyAPI/logs"
      - "../files/plugins:/CLIProxyAPI/plugins"
    restart: unless-stopped
